version: '3.8'

services:

  web:
    build: .
    command:
      bash -c "poetry run alembic upgrade head &&
      poetry run uvicorn app.main:app --reload --host 0.0.0.0 --port 8000"
    volumes:
      - ./project:/usr/src/app/test_bewise
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql+asyncpg://root:123@db:5432/database
    depends_on:
      - db

  db:
    image: postgres:13.4
    expose:
      - 5432
    volumes:
      - /data/postgresql:/var/lib/postgresql
      - /data/postgresql/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=database